name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
      
#    - name: Run tests
#      run: cargo test --verbose

    - name: Compress output
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: ./target/release
        files: |
          ./mkimage
        outPath: mkimage.linux-amd64.tar.gz

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
#        release_name: ${{ steps.version.outputs.version }}
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
#        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/mkimage.linux-amd64.tar.gz
        asset_name: mkimage.linux-amd64.tar.gz
        asset_content_type: application/gzip
